# Generated by Django 6.0.7 on 2026-08-26 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reanBio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
