# Generated by Django 6.0.7 on 2026-08-26 07:04

import django.db.models.deletion
import reanBio.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reanBio', '0002_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อห้องเรียน')),
                ('code', models.CharField(default=reanBio.models.generate_classroom_code, max_length=6, unique=True, verbose_name='รหัสห้องเรียน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, related_name='joined_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='นักเรียน')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='คุณครูผู้สอน')),
            ],
        ),
    ]
