# Generated by Django 6.0.7 on 2026-08-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reanBio', '0003_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อบทเรียน')),
                ('grade', models.CharField(choices=[('m4', 'ม.4'), ('m5', 'ม.5'), ('m6', 'ม.6')], max_length=2, verbose_name='ระดับชั้น')),
                ('icon', models.CharField(default='🧬', max_length=10, verbose_name='อีโมจิประจำบท')),
                ('description', models.TextField(verbose_name='คำอธิบายย่อย')),
                ('sub_lessons_count', models.PositiveIntegerField(default=1, verbose_name='จำนวนบทเรียนย่อย')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='ระยะเวลาเรียน (นาที)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ลำดับการแสดงผล')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['grade', 'order'],
            },
        ),
    ]
