# Generated by Django 6.0.7 on 2026-08-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reanBio", "0004_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="content",
            field=models.TextField(
                blank=True, default="", verbose_name="เนื้อหาบทเรียนแบบเต็ม"
            ),
        ),
    ]
