# Generated by Django 6.0.7 on 2026-08-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reanBio", "0006_seed_m4_lessons"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="diagram_svg",
            field=models.TextField(
                blank=True, default="", verbose_name="ภาพประกอบ (SVG)"
            ),
        ),
    ]
