# Generated by Django 6.0.7 on 2026-08-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reanBio", "0008_seed_m4_diagrams"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["grade", "chapter", "subtopic_code", "order"]},
        ),
        migrations.AddField(
            model_name="lesson",
            name="chapter",
            field=models.PositiveIntegerField(
                default=1, verbose_name="บทที่ (ตามหนังสือเรียน)"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="chapter_title",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="ชื่อบทใหญ่"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="subtopic_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=10,
                verbose_name="เลขหัวข้อย่อย เช่น 1.1",
            ),
        ),
    ]
