# Generated by Django 6.0.7 on 2026-08-28 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reanBio", "0010_restructure_m4_chapter1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("practice", "แบบฝึกหัด"), ("exam", "ข้อสอบ")],
                        default="practice",
                        max_length=10,
                        verbose_name="ประเภทการทำ",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=2,
                        verbose_name="ระดับชั้น (สำหรับข้อสอบ)",
                    ),
                ),
                (
                    "chapter",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="บทที่ (สำหรับข้อสอบ)"
                    ),
                ),
                ("score", models.FloatField(default=0, verbose_name="คะแนนที่ได้")),
                ("max_score", models.FloatField(default=0, verbose_name="คะแนนเต็ม")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="เวลาที่ส่งคำตอบ"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempts",
                        to="reanBio.lesson",
                        verbose_name="บทเรียน (สำหรับแบบฝึกหัด)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ทำ",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="ลำดับข้อ"),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "ปรนัย (เลือกคำตอบ)"),
                            ("text", "อัตนัย (พิมพ์คำตอบ)"),
                        ],
                        default="mcq",
                        max_length=4,
                        verbose_name="ประเภทคำถาม",
                    ),
                ),
                ("text", models.TextField(verbose_name="โจทย์คำถาม")),
                (
                    "explanation",
                    models.TextField(
                        blank=True, default="", verbose_name="คำอธิบาย/เฉลย"
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=1, verbose_name="คะแนนเต็มของข้อนี้"
                    ),
                ),
                (
                    "accepted_answers",
                    models.JSONField(
                        blank=True, default=list, verbose_name="คำตอบที่ยอมรับ (อัตนัย)"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="reanBio.lesson",
                        verbose_name="บทเรียนที่เกี่ยวข้อง",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson", "order"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, verbose_name="ลำดับตัวเลือก"
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=500, verbose_name="ข้อความตัวเลือก"),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, verbose_name="เป็นคำตอบที่ถูกต้อง"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="reanBio.question",
                        verbose_name="คำถาม",
                    ),
                ),
            ],
            options={
                "ordering": ["question", "order"],
            },
        ),
        migrations.CreateModel(
            name="AttemptAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, verbose_name="ลำดับที่แสดงในการทำครั้งนี้"
                    ),
                ),
                (
                    "text_answer",
                    models.TextField(
                        blank=True, default="", verbose_name="คำตอบที่พิมพ์"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="ตอบถูกหรือไม่"),
                ),
                (
                    "points_earned",
                    models.FloatField(default=0, verbose_name="คะแนนที่ได้ในข้อนี้"),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="reanBio.attempt",
                        verbose_name="การทำแบบฝึกหัด/ข้อสอบ",
                    ),
                ),
                (
                    "selected_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reanBio.choice",
                        verbose_name="ตัวเลือกที่เลือก",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempt_answers",
                        to="reanBio.question",
                        verbose_name="คำถาม",
                    ),
                ),
            ],
            options={
                "ordering": ["attempt", "order"],
            },
        ),
    ]
