# Generated by Django 6.0.7 on 2026-08-28 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reanBio", "0012_seed_chapter1_questions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "after_paragraph",
                    models.PositiveIntegerField(
                        default=1, verbose_name="แทรกหลังย่อหน้าที่ (นับจาก 1)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, verbose_name="ลำดับ (ถ้ามีหลายข้อในตำแหน่งเดียวกัน)"
                    ),
                ),
                ("text", models.TextField(verbose_name="คำถามสั้นๆ ระหว่างอ่าน")),
                (
                    "explanation",
                    models.TextField(
                        blank=True, default="", verbose_name="คำอธิบายเพิ่มเติม"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="reanBio.lesson",
                        verbose_name="บทเรียนที่เกี่ยวข้อง",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson", "after_paragraph", "order"],
            },
        ),
        migrations.CreateModel(
            name="CheckpointChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "text",
                    models.CharField(max_length=300, verbose_name="ข้อความตัวเลือก"),
                ),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "checkpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="reanBio.checkpoint",
                        verbose_name="คำถามระหว่างอ่าน",
                    ),
                ),
            ],
            options={
                "ordering": ["checkpoint", "order"],
            },
        ),
    ]
