# Generated by Django 6.0.7 on 2026-08-31 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reanBio", "0014_expand_chapter1_content_and_checkpoints"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="เข้าชมล่าสุดเมื่อ"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="reanBio.lesson",
                        verbose_name="บทเรียนที่เข้าชม",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้งาน",
                    ),
                ),
            ],
            options={
                "ordering": ["-viewed_at"],
                "unique_together": {("user", "lesson")},
            },
        ),
    ]
